// Code generated by "stringer -type OpType"; DO NOT EDIT.

package fsbroker

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Create-0]
	_ = x[Write-1]
	_ = x[Rename-2]
	_ = x[Remove-3]
	_ = x[Chmod-4]
	_ = x[NoOp-5]
}

const _OpType_name = "CreateWriteRenameRemoveChmodNoOp"

var _OpType_index = [...]uint8{0, 6, 11, 17, 23, 28, 32}

func (i OpType) String() string {
	if i < 0 || i >= OpType(len(_OpType_index)-1) {
		return "OpType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _OpType_name[_OpType_index[i]:_OpType_index[i+1]]
}
